#cloud-config
hostname: ubuntu.robert.local
manage_etc_hosts: true
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 YOUR_PUBLIC_SSH_KEY_HERE
chpasswd:
  list: |
    ubuntu:stephane
  expire: false
